# **Classificação de Dados**

**Objetivo**

* Construindo modelo para classificação das especies de flores com o conjunto de dados Iris

## **1. Introdução**

<p align="justify">
A classificação de espécies de flores é um desafio clássico e fundamental no campo da aprendizagem de máquina. Neste projeto, exploraremos a aplicação do algoritmo K-Nearest Neighbors (KNN) para abordar essa tarefa, utilizando o conjunto de dados Iris. O objetivo principal é desenvolver um modelo de classificação preciso que seja capaz de distinguir entre três espécies de flores com base em um conjunto de atributos específicos.

<p align="justify">
O conjunto de dados Iris é amplamente reconhecido e utilizado em projetos de aprendizado de máquina, devido à sua simplicidade e relevância. Ele consiste em medidas de quatro características botânicas de diferentes amostras de flores Iris, juntamente com suas respectivas espécies: Iris-setosa, Iris-versicolor e Iris-virginica. Essas características incluem o comprimento e largura das sépalas e pétalas.

<p align="justify">
O algoritmo K-Nearest Neighbors (KNN) é uma escolha adequada para este projeto, uma vez que é um método de classificação simples, mas eficaz, que se baseia na proximidade dos pontos de dados no espaço de características. O KNN atribui a classe de uma amostra com base na classe majoritária das K amostras mais próximas no conjunto de treinamento. Esta abordagem torna o KNN particularmente útil para conjuntos de dados de classificação, como o conjunto de dados Iris, onde a similaridade entre amostras desempenha um papel crucial na diferenciação das espécies.

In [ ]:
# Carregando bibliotecas

import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt

from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [ ]:
# Carregando base de dados

dados = pd.read_csv('/content/drive/MyDrive/Portfólio/Dados/Iris_Dataset.csv')

In [ ]:
# Visualização dados

dados.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

## **2. Análise Exploratória de Dados**

In [ ]:
# 2.1 Informações sobre o dataset

dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
# 2.2 Verificando a existência de valores faltantes

dados.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# 2.3 Estatística descritiva dos dados

dados.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
# 2.4 Gráfico 1: sepal_width x sepal_length

fig = px.scatter(dados,
                 x = 'sepal_width',
                 y = 'sepal_length',
                 color = 'species')
fig.show()

In [ ]:
# 2.5 Gráfico 2: sepal_width x sepal_length

fig = px.scatter(dados,
                 x = 'petal_width',
                 y = 'petal_length',
                 color = 'species')
fig.show()

## **3. Pré-Processamento de Dados**

In [ ]:
# 3.1 Separando os dados em previsores e classes

previsores = np.array(dados.drop('species', axis = 1))
classes = dados['species']

In [ ]:
# 3.2 Dividindo os dados em treino (70%) e teste (30%)

X_treino, X_teste, y_treino, y_teste = train_test_split(previsores,
                                                        classes,
                                                        test_size = 0.3,
                                                        random_state = 0)

In [ ]:
# 3.3 Verificando a distribuição dos dados em treino e teste

print(X_treino.shape)
print(y_treino.shape)
print(X_teste.shape)
print(y_teste.shape)

(105, 4)
(105,)
(45, 4)
(45,)

## **4. Construindo Modelo KNN**

<p align="justify">
A escolha do modelo se deu pelo fato da sua simplicidade e eficácia, principalmente em conjuntos de dados pequenos.

In [ ]:
# 4.1 Instânciando modelo

modelo = KNeighborsClassifier()

In [ ]:
# 4.2 Treinando o modelo

modelo.fit(X_treino, y_treino)

KNeighborsClassifier()

In [ ]:
# 4.3 Aplicando modelo treinado aos dados de teste: realizando previsões

y_pred = modelo.predict(X_teste)

## **5. Avaliando e Testando o Modelo**

In [ ]:
# 5.1 Métricas de Avaliação

print(classification_report(y_teste, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.94      0.97        18
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

In [ ]:
# 5.2 Matriz de Confusão

print(pd.crosstab(y_teste,
                  y_pred,
                  rownames = ['Real'],
                  colnames = ['Previsto']))

Previsto         Iris-setosa  Iris-versicolor  Iris-virginica
Real
Iris-setosa               16                0               0
Iris-versicolor            0               17               1
Iris-virginica             0                0              11

In [ ]:
# 5.3 Aplicando modelo a novos dados

## Novos dados
new_data = np.array([[5.1, 3.5, 1.4, 0.2],
                [6.3, 3.3, 5.0, 1.6],
                [5.0, 3.6, 1.4, 0.2]])

## Realizando previsão
previsores = modelo.predict(new_data)

## Resultado
print('**** Classificação ****\n {} \n {} \n {}'.format(previsores[0],
                                                        previsores[1],
                                                        previsores[2]))

**** Classificação ****
 Iris-setosa
 Iris-versicolor
 Iris-setosa

## **6. Considerações Finais**

<p align="justify">
O projeto de classificação de espécies de flores do conjunto de dados Iris usando o algoritmo KNN obteve um desempenho muito bom. Isso é um indicativo do poder da aprendizagem de máquina para resolver problemas de classificação, mesmo em conjuntos de dados relativamente simples.

<p align="justify">
A escolha do algoritmo KNN foi baseada em sua simplicidade e eficácia, especialmente em conjuntos de dados pequenos a médios. O KNN se mostrou uma escolha sólida para este projeto de classificação de espécies de flores, e sua flexibilidade permitiu ajustar o número de vizinhos para otimizar o desempenho.

<p align="justify">
Durante o projeto, realizamos uma avaliação rigorosa do desempenho do modelo. Isso incluiu métricas como acurácia, precisão, recall, F1-score e matriz de confusão. Essas métricas nos permitiram entender o quão bem o modelo estava classificando as diferentes espécies de flores.